### ISSUE TITLE
Way to check if SPECIFIC grimoire card is unlocked?

### ISSUE THREAD

**Issue by EbearPlays** [sebastianbarfurth/destiny-php#13]
Self explanatory based on the title. Is there any way to check if a player has unlocked a specific card?

This could be useful if players are looking to use a website to see if they unlocked a certain grimoire.

Is this possible? If it is, how would I do this?

**Comment by sebastianbarfurth** [comment]
I will see what I can do.

**Comment by sebastianbarfurth** [comment]
There is no endpoint for this, you would need to use the data returned by the ``fetchGrimoireData`` method as described here: [Grimoire Data](https://github.com/sebastianbarfurth/destiny-php#grimoire-data)
