### ISSUE TITLE
Destiny\Support\Exceptions\PlayerNotFoundException

### ISSUE THREAD

**Issue by squidv3** [sebastianbarfurth/destiny-php#14]
Why I'm having this error

Fatal error: Uncaught exception 'Destiny\Support\Exceptions\PlayerNotFoundException' in /home/desti501/public_html/2/custom/2/vendor/sebastianbarfurth/destiny/src/Destiny/Destiny.php:42 Stack trace: #0 /home/desti501/public_html/2/custom/2/vendor/sebastianbarfurth/destiny/src/Destiny/Destiny.php(82): Destiny\Destiny->fetchPlayer('aFreshMelon', 1) #1 /home/desti501/public_html/2/custom/2/index.php(10): Destiny\Destiny->fetchXboxPlayer('aFreshMelon') #2 {main} thrown in /home/desti501/public_html/2/custom/2/vendor/sebastianbarfurth/destiny/src/Destiny/Destiny.php on line 42

**Comment by sebastianbarfurth** [comment]
Fixed with 89957b6a9cb3eaa2932552e9e5dbea7e5677a33c
