### ISSUE TITLE
Support authentication

### ISSUE THREAD

**Issue by rpmobile** [sebastianbarfurth/destiny-php#4]
This is a feature request to support authentication with XBox Live / PSN.  I know there are scripts that do this, but many seem to be broken or unsupported.

**Comment by aFreshMelon** [comment]
Authentication is a bit tricky since there isn't really an API, you have to fiddle with cookies quite a bit.

I will look into a wrapper for throwing the cookies at bungie for requests, but I can't promise anything too soon.
